/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.hadoop.hive.metastore.api;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.log4j.Logger;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;

public class DbPriv implements TBase, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("DbPriv");
  private static final TField USER_NAME_FIELD_DESC = new TField("userName", TType.STRING, (short)1);
  private static final TField DB_NAME_FIELD_DESC = new TField("dbName", TType.STRING, (short)2);
  private static final TField SELECT_PRIV_FIELD_DESC = new TField("select_priv", TType.BOOL, (short)3);
  private static final TField INSERT_PRIV_FIELD_DESC = new TField("insert_priv", TType.BOOL, (short)4);
  private static final TField DROP_PRIV_FIELD_DESC = new TField("drop_priv", TType.BOOL, (short)5);
  private static final TField GRANT_PRIV_FIELD_DESC = new TField("grant_priv", TType.BOOL, (short)6);
  private static final TField ALTER_PRIV_FIELD_DESC = new TField("alter_priv", TType.BOOL, (short)7);
  private static final TField CREATE_PRIV_FIELD_DESC = new TField("create_priv", TType.BOOL, (short)8);

  private String userName;
  public static final int USERNAME = 1;
  private String dbName;
  public static final int DBNAME = 2;
  private boolean select_priv;
  public static final int SELECT_PRIV = 3;
  private boolean insert_priv;
  public static final int INSERT_PRIV = 4;
  private boolean drop_priv;
  public static final int DROP_PRIV = 5;
  private boolean grant_priv;
  public static final int GRANT_PRIV = 6;
  private boolean alter_priv;
  public static final int ALTER_PRIV = 7;
  private boolean create_priv;
  public static final int CREATE_PRIV = 8;

  private final Isset __isset = new Isset();
  private static final class Isset implements java.io.Serializable {
    public boolean select_priv = false;
    public boolean insert_priv = false;
    public boolean drop_priv = false;
    public boolean grant_priv = false;
    public boolean alter_priv = false;
    public boolean create_priv = false;
  }

  public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
    put(USERNAME, new FieldMetaData("userName", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    put(DBNAME, new FieldMetaData("dbName", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    put(SELECT_PRIV, new FieldMetaData("select_priv", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
    put(INSERT_PRIV, new FieldMetaData("insert_priv", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
    put(DROP_PRIV, new FieldMetaData("drop_priv", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
    put(GRANT_PRIV, new FieldMetaData("grant_priv", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
    put(ALTER_PRIV, new FieldMetaData("alter_priv", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
    put(CREATE_PRIV, new FieldMetaData("create_priv", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
  }});

  static {
    FieldMetaData.addStructMetaDataMap(DbPriv.class, metaDataMap);
  }

  public DbPriv() {
  }

  public DbPriv(
    String userName,
    String dbName,
    boolean select_priv,
    boolean insert_priv,
    boolean drop_priv,
    boolean grant_priv,
    boolean alter_priv,
    boolean create_priv)
  {
    this();
    this.userName = userName;
    this.dbName = dbName;
    this.select_priv = select_priv;
    this.__isset.select_priv = true;
    this.insert_priv = insert_priv;
    this.__isset.insert_priv = true;
    this.drop_priv = drop_priv;
    this.__isset.drop_priv = true;
    this.grant_priv = grant_priv;
    this.__isset.grant_priv = true;
    this.alter_priv = alter_priv;
    this.__isset.alter_priv = true;
    this.create_priv = create_priv;
    this.__isset.create_priv = true;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DbPriv(DbPriv other) {
    if (other.isSetUserName()) {
      this.userName = other.userName;
    }
    if (other.isSetDbName()) {
      this.dbName = other.dbName;
    }
    __isset.select_priv = other.__isset.select_priv;
    this.select_priv = other.select_priv;
    __isset.insert_priv = other.__isset.insert_priv;
    this.insert_priv = other.insert_priv;
    __isset.drop_priv = other.__isset.drop_priv;
    this.drop_priv = other.drop_priv;
    __isset.grant_priv = other.__isset.grant_priv;
    this.grant_priv = other.grant_priv;
    __isset.alter_priv = other.__isset.alter_priv;
    this.alter_priv = other.alter_priv;
    __isset.create_priv = other.__isset.create_priv;
    this.create_priv = other.create_priv;
  }

  @Override
  public DbPriv clone() {
    return new DbPriv(this);
  }

  public String getUserName() {
    return this.userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public void unsetUserName() {
    this.userName = null;
  }

  // Returns true if field userName is set (has been asigned a value) and false otherwise
  public boolean isSetUserName() {
    return this.userName != null;
  }

  public String getDbName() {
    return this.dbName;
  }

  public void setDbName(String dbName) {
    this.dbName = dbName;
  }

  public void unsetDbName() {
    this.dbName = null;
  }

  // Returns true if field dbName is set (has been asigned a value) and false otherwise
  public boolean isSetDbName() {
    return this.dbName != null;
  }

  public boolean isSelect_priv() {
    return this.select_priv;
  }

  public void setSelect_priv(boolean select_priv) {
    this.select_priv = select_priv;
    this.__isset.select_priv = true;
  }

  public void unsetSelect_priv() {
    this.__isset.select_priv = false;
  }

  // Returns true if field select_priv is set (has been asigned a value) and false otherwise
  public boolean isSetSelect_priv() {
    return this.__isset.select_priv;
  }

  public boolean isInsert_priv() {
    return this.insert_priv;
  }

  public void setInsert_priv(boolean insert_priv) {
    this.insert_priv = insert_priv;
    this.__isset.insert_priv = true;
  }

  public void unsetInsert_priv() {
    this.__isset.insert_priv = false;
  }

  // Returns true if field insert_priv is set (has been asigned a value) and false otherwise
  public boolean isSetInsert_priv() {
    return this.__isset.insert_priv;
  }

  public boolean isDrop_priv() {
    return this.drop_priv;
  }

  public void setDrop_priv(boolean drop_priv) {
    this.drop_priv = drop_priv;
    this.__isset.drop_priv = true;
  }

  public void unsetDrop_priv() {
    this.__isset.drop_priv = false;
  }

  // Returns true if field drop_priv is set (has been asigned a value) and false otherwise
  public boolean isSetDrop_priv() {
    return this.__isset.drop_priv;
  }

  public boolean isGrant_priv() {
    return this.grant_priv;
  }

  public void setGrant_priv(boolean grant_priv) {
    this.grant_priv = grant_priv;
    this.__isset.grant_priv = true;
  }

  public void unsetGrant_priv() {
    this.__isset.grant_priv = false;
  }

  // Returns true if field grant_priv is set (has been asigned a value) and false otherwise
  public boolean isSetGrant_priv() {
    return this.__isset.grant_priv;
  }

  public boolean isAlter_priv() {
    return this.alter_priv;
  }

  public void setAlter_priv(boolean alter_priv) {
    this.alter_priv = alter_priv;
    this.__isset.alter_priv = true;
  }

  public void unsetAlter_priv() {
    this.__isset.alter_priv = false;
  }

  // Returns true if field alter_priv is set (has been asigned a value) and false otherwise
  public boolean isSetAlter_priv() {
    return this.__isset.alter_priv;
  }

  public boolean isCreate_priv() {
    return this.create_priv;
  }

  public void setCreate_priv(boolean create_priv) {
    this.create_priv = create_priv;
    this.__isset.create_priv = true;
  }

  public void unsetCreate_priv() {
    this.__isset.create_priv = false;
  }

  // Returns true if field create_priv is set (has been asigned a value) and false otherwise
  public boolean isSetCreate_priv() {
    return this.__isset.create_priv;
  }

  public void setFieldValue(int fieldID, Object value) {
    switch (fieldID) {
    case USERNAME:
      if (value == null) {
        unsetUserName();
      } else {
        setUserName((String)value);
      }
      break;

    case DBNAME:
      if (value == null) {
        unsetDbName();
      } else {
        setDbName((String)value);
      }
      break;

    case SELECT_PRIV:
      if (value == null) {
        unsetSelect_priv();
      } else {
        setSelect_priv((Boolean)value);
      }
      break;

    case INSERT_PRIV:
      if (value == null) {
        unsetInsert_priv();
      } else {
        setInsert_priv((Boolean)value);
      }
      break;

    case DROP_PRIV:
      if (value == null) {
        unsetDrop_priv();
      } else {
        setDrop_priv((Boolean)value);
      }
      break;

    case GRANT_PRIV:
      if (value == null) {
        unsetGrant_priv();
      } else {
        setGrant_priv((Boolean)value);
      }
      break;

    case ALTER_PRIV:
      if (value == null) {
        unsetAlter_priv();
      } else {
        setAlter_priv((Boolean)value);
      }
      break;

    case CREATE_PRIV:
      if (value == null) {
        unsetCreate_priv();
      } else {
        setCreate_priv((Boolean)value);
      }
      break;

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  public Object getFieldValue(int fieldID) {
    switch (fieldID) {
    case USERNAME:
      return getUserName();

    case DBNAME:
      return getDbName();

    case SELECT_PRIV:
      return new Boolean(isSelect_priv());

    case INSERT_PRIV:
      return new Boolean(isInsert_priv());

    case DROP_PRIV:
      return new Boolean(isDrop_priv());

    case GRANT_PRIV:
      return new Boolean(isGrant_priv());

    case ALTER_PRIV:
      return new Boolean(isAlter_priv());

    case CREATE_PRIV:
      return new Boolean(isCreate_priv());

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
  public boolean isSet(int fieldID) {
    switch (fieldID) {
    case USERNAME:
      return isSetUserName();
    case DBNAME:
      return isSetDbName();
    case SELECT_PRIV:
      return isSetSelect_priv();
    case INSERT_PRIV:
      return isSetInsert_priv();
    case DROP_PRIV:
      return isSetDrop_priv();
    case GRANT_PRIV:
      return isSetGrant_priv();
    case ALTER_PRIV:
      return isSetAlter_priv();
    case CREATE_PRIV:
      return isSetCreate_priv();
    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DbPriv)
      return this.equals((DbPriv)that);
    return false;
  }

  public boolean equals(DbPriv that) {
    if (that == null)
      return false;

    boolean this_present_userName = true && this.isSetUserName();
    boolean that_present_userName = true && that.isSetUserName();
    if (this_present_userName || that_present_userName) {
      if (!(this_present_userName && that_present_userName))
        return false;
      if (!this.userName.equals(that.userName))
        return false;
    }

    boolean this_present_dbName = true && this.isSetDbName();
    boolean that_present_dbName = true && that.isSetDbName();
    if (this_present_dbName || that_present_dbName) {
      if (!(this_present_dbName && that_present_dbName))
        return false;
      if (!this.dbName.equals(that.dbName))
        return false;
    }

    boolean this_present_select_priv = true;
    boolean that_present_select_priv = true;
    if (this_present_select_priv || that_present_select_priv) {
      if (!(this_present_select_priv && that_present_select_priv))
        return false;
      if (this.select_priv != that.select_priv)
        return false;
    }

    boolean this_present_insert_priv = true;
    boolean that_present_insert_priv = true;
    if (this_present_insert_priv || that_present_insert_priv) {
      if (!(this_present_insert_priv && that_present_insert_priv))
        return false;
      if (this.insert_priv != that.insert_priv)
        return false;
    }

    boolean this_present_drop_priv = true;
    boolean that_present_drop_priv = true;
    if (this_present_drop_priv || that_present_drop_priv) {
      if (!(this_present_drop_priv && that_present_drop_priv))
        return false;
      if (this.drop_priv != that.drop_priv)
        return false;
    }

    boolean this_present_grant_priv = true;
    boolean that_present_grant_priv = true;
    if (this_present_grant_priv || that_present_grant_priv) {
      if (!(this_present_grant_priv && that_present_grant_priv))
        return false;
      if (this.grant_priv != that.grant_priv)
        return false;
    }

    boolean this_present_alter_priv = true;
    boolean that_present_alter_priv = true;
    if (this_present_alter_priv || that_present_alter_priv) {
      if (!(this_present_alter_priv && that_present_alter_priv))
        return false;
      if (this.alter_priv != that.alter_priv)
        return false;
    }

    boolean this_present_create_priv = true;
    boolean that_present_create_priv = true;
    if (this_present_create_priv || that_present_create_priv) {
      if (!(this_present_create_priv && that_present_create_priv))
        return false;
      if (this.create_priv != that.create_priv)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case USERNAME:
          if (field.type == TType.STRING) {
            this.userName = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case DBNAME:
          if (field.type == TType.STRING) {
            this.dbName = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case SELECT_PRIV:
          if (field.type == TType.BOOL) {
            this.select_priv = iprot.readBool();
            this.__isset.select_priv = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case INSERT_PRIV:
          if (field.type == TType.BOOL) {
            this.insert_priv = iprot.readBool();
            this.__isset.insert_priv = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case DROP_PRIV:
          if (field.type == TType.BOOL) {
            this.drop_priv = iprot.readBool();
            this.__isset.drop_priv = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case GRANT_PRIV:
          if (field.type == TType.BOOL) {
            this.grant_priv = iprot.readBool();
            this.__isset.grant_priv = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ALTER_PRIV:
          if (field.type == TType.BOOL) {
            this.alter_priv = iprot.readBool();
            this.__isset.alter_priv = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case CREATE_PRIV:
          if (field.type == TType.BOOL) {
            this.create_priv = iprot.readBool();
            this.__isset.create_priv = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.userName != null) {
      oprot.writeFieldBegin(USER_NAME_FIELD_DESC);
      oprot.writeString(this.userName);
      oprot.writeFieldEnd();
    }
    if (this.dbName != null) {
      oprot.writeFieldBegin(DB_NAME_FIELD_DESC);
      oprot.writeString(this.dbName);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(SELECT_PRIV_FIELD_DESC);
    oprot.writeBool(this.select_priv);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(INSERT_PRIV_FIELD_DESC);
    oprot.writeBool(this.insert_priv);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(DROP_PRIV_FIELD_DESC);
    oprot.writeBool(this.drop_priv);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(GRANT_PRIV_FIELD_DESC);
    oprot.writeBool(this.grant_priv);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(ALTER_PRIV_FIELD_DESC);
    oprot.writeBool(this.alter_priv);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(CREATE_PRIV_FIELD_DESC);
    oprot.writeBool(this.create_priv);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DbPriv(");
    boolean first = true;

    sb.append("userName:");
    if (this.userName == null) {
      sb.append("null");
    } else {
      sb.append(this.userName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dbName:");
    if (this.dbName == null) {
      sb.append("null");
    } else {
      sb.append(this.dbName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("select_priv:");
    sb.append(this.select_priv);
    first = false;
    if (!first) sb.append(", ");
    sb.append("insert_priv:");
    sb.append(this.insert_priv);
    first = false;
    if (!first) sb.append(", ");
    sb.append("drop_priv:");
    sb.append(this.drop_priv);
    first = false;
    if (!first) sb.append(", ");
    sb.append("grant_priv:");
    sb.append(this.grant_priv);
    first = false;
    if (!first) sb.append(", ");
    sb.append("alter_priv:");
    sb.append(this.alter_priv);
    first = false;
    if (!first) sb.append(", ");
    sb.append("create_priv:");
    sb.append(this.create_priv);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

